package migrate

// Column is the fluent handle returned by column declarations. Modifiers
// return the same handle so declarations chain:
//
//	t.String("email").Nullable().Default("unknown").Unique()
type Column struct {
	def *columnDef
}

// Nullable allows NULL values. Columns are NOT NULL by default: required-ness
// is the safer starting point for schema design, and opting out is explicit.
func (c *Column) Nullable() *Column {
	c.def.nullable = true
	return c
}

// Default sets a literal default value, rendered safely for the dialect:
// strings are quoted, booleans become the dialect's literal, nil means NULL.
// For an SQL expression, use DefaultExpr.
func (c *Column) Default(value any) *Column {
	c.def.hasDefault = true
	c.def.defaultVal = value
	return c
}

// DefaultExpr sets a default SQL expression, written verbatim:
//
//	t.UUID("token").DefaultExpr("gen_random_uuid()")
func (c *Column) DefaultExpr(expr string) *Column {
	c.def.hasDefault = true
	c.def.defaultExpr = expr
	return c
}

// UseCurrent defaults the column to the current timestamp.
func (c *Column) UseCurrent() *Column {
	c.def.useCurrent = true
	return c
}

// UseCurrentOnUpdate makes MySQL refresh the column to the current timestamp
// whenever the row is updated. Other dialects have no equivalent and ignore
// it; use a trigger or set the value in application code instead.
func (c *Column) UseCurrentOnUpdate() *Column {
	c.def.useCurrentOnUpdate = true
	return c
}

// Unsigned restricts an integer column to non-negative values on MySQL.
// Postgres and SQLite have no unsigned types and ignore it.
func (c *Column) Unsigned() *Column {
	c.def.unsigned = true
	return c
}

// AutoIncrement makes an integer column the table's auto-incrementing primary
// key, generated by the database: an identity column on Postgres
// (GENERATED BY DEFAULT AS IDENTITY), AUTO_INCREMENT on MySQL, INTEGER
// PRIMARY KEY AUTOINCREMENT on SQLite. ID declares the conventional 64-bit
// form in one call.
//
// Auto-increment implies the primary key — MySQL and SQLite accept nothing
// else — so it cannot combine with other primary key declarations, defaults
// or Nullable.
func (c *Column) AutoIncrement() *Column {
	c.def.autoIncr = true
	c.def.primary = true
	return c
}

// Primary makes this column the table's primary key. ID declares the usual
// auto-incrementing key; Primary suits natural keys like a code or UUID.
func (c *Column) Primary() *Column {
	c.def.primary = true
	return c
}

// Unique adds a unique index on this column, named {table}_{column}_unique.
func (c *Column) Unique() *Column {
	c.def.unique = true
	return c
}

// Index adds an index on this column, named {table}_{column}_index.
func (c *Column) Index() *Column {
	c.def.indexed = true
	return c
}

// Comment attaches a comment to the column. SQLite has no column comments and
// ignores it.
func (c *Column) Comment(comment string) *Column {
	c.def.comment = comment
	return c
}

// After places the column after an existing one when altering a MySQL table.
// Column order is cosmetic; other dialects ignore it.
func (c *Column) After(column string) *Column {
	c.def.after = column
	return c
}

// First places the column first when altering a MySQL table. Column order is
// cosmetic; other dialects ignore it.
func (c *Column) First() *Column {
	c.def.first = true
	return c
}

// Index is the fluent handle returned by Table.Index and Table.Unique.
type Index struct {
	def *indexDef
}

// Name overrides the conventional {table}_{columns}_{index|unique} name.
// A named index must be dropped with DropIndexByName.
func (i *Index) Name(name string) *Index {
	i.def.name = name
	return i
}

// ForeignKey is the fluent handle returned by Table.Foreign.
type ForeignKey struct {
	def   *foreignDef
	table *Table
}

// References sets the parent table and columns; columns default to "id".
func (f *ForeignKey) References(table string, columns ...string) *ForeignKey {
	f.def.refTable = table
	f.def.refColumns = columns
	if len(columns) == 0 {
		f.def.refColumns = []string{"id"}
	}
	return f
}

// Name overrides the conventional {table}_{columns}_foreign name. A named key
// must be dropped with DropForeignByName.
func (f *ForeignKey) Name(name string) *ForeignKey {
	f.def.name = name
	return f
}

// CascadeOnDelete deletes child rows when the parent row is deleted.
func (f *ForeignKey) CascadeOnDelete() *ForeignKey { f.def.onDelete = "CASCADE"; return f }

// RestrictOnDelete rejects deleting a parent row that still has children.
func (f *ForeignKey) RestrictOnDelete() *ForeignKey { f.def.onDelete = "RESTRICT"; return f }

// NullOnDelete sets the child columns to NULL when the parent row is deleted.
func (f *ForeignKey) NullOnDelete() *ForeignKey { f.def.onDelete = "SET NULL"; return f }

// NoActionOnDelete leaves enforcement to the end of the statement (or
// transaction, where supported).
func (f *ForeignKey) NoActionOnDelete() *ForeignKey { f.def.onDelete = "NO ACTION"; return f }

// CascadeOnUpdate propagates key updates to child rows.
func (f *ForeignKey) CascadeOnUpdate() *ForeignKey { f.def.onUpdate = "CASCADE"; return f }

// RestrictOnUpdate rejects updating a key that still has children.
func (f *ForeignKey) RestrictOnUpdate() *ForeignKey { f.def.onUpdate = "RESTRICT"; return f }

// NullOnUpdate sets the child columns to NULL when the parent key changes.
func (f *ForeignKey) NullOnUpdate() *ForeignKey { f.def.onUpdate = "SET NULL"; return f }

// ForeignColumn is the fluent handle returned by Table.ForeignID: a Column
// that can also declare the foreign key constraint tying it to its parent.
type ForeignColumn struct {
	*Column
	table *Table
	fk    *ForeignKey // non-nil once Constrained or References was called
}

// Constrained adds the foreign key constraint, inferring the parent table
// from the column name (user_id → users) unless one is given. The referenced
// column is "id".
func (fc *ForeignColumn) Constrained(table ...string) *ForeignColumn {
	parent := optional(table, "")
	if parent == "" {
		parent = guessParentTable(fc.def.name)
		if parent == "" {
			fc.table.errf("cannot infer the parent table of column %q; pass it to Constrained explicitly", fc.def.name)
		}
	}
	return fc.References(parent, "id")
}

// References adds the foreign key constraint with an explicit parent table
// and columns; columns default to "id".
func (fc *ForeignColumn) References(table string, columns ...string) *ForeignColumn {
	if fc.fk == nil {
		fc.fk = fc.table.Foreign(fc.def.name)
	}
	fc.fk.References(table, columns...)
	return fc
}

func (fc *ForeignColumn) constrainedOnly(method string) {
	if fc.fk == nil {
		fc.table.errf("%s on column %q requires Constrained or References first", method, fc.def.name)
	}
}

// CascadeOnDelete deletes child rows when the parent row is deleted.
func (fc *ForeignColumn) CascadeOnDelete() *ForeignColumn {
	fc.constrainedOnly("CascadeOnDelete")
	if fc.fk != nil {
		fc.fk.CascadeOnDelete()
	}
	return fc
}

// RestrictOnDelete rejects deleting a parent row that still has children.
func (fc *ForeignColumn) RestrictOnDelete() *ForeignColumn {
	fc.constrainedOnly("RestrictOnDelete")
	if fc.fk != nil {
		fc.fk.RestrictOnDelete()
	}
	return fc
}

// NullOnDelete sets the column to NULL when the parent row is deleted.
func (fc *ForeignColumn) NullOnDelete() *ForeignColumn {
	fc.constrainedOnly("NullOnDelete")
	if fc.fk != nil {
		fc.fk.NullOnDelete()
	}
	return fc
}

// Nullable allows NULL values, shadowing Column.Nullable to keep the chain.
func (fc *ForeignColumn) Nullable() *ForeignColumn {
	fc.Column.Nullable()
	return fc
}

// Unique adds a unique index on the column, shadowing Column.Unique to keep
// the chain.
func (fc *ForeignColumn) Unique() *ForeignColumn {
	fc.Column.Unique()
	return fc
}

// Index adds an index on the column, shadowing Column.Index to keep the chain.
func (fc *ForeignColumn) Index() *ForeignColumn {
	fc.Column.Index()
	return fc
}
