package migrate

import (
	"errors"
	"strings"
	"testing"
)

// compileSchema runs fn against a fresh Schema and compiles the recorded
// operations for d, returning the SQL texts. Opaque fn statements render as
// "-- " plus their description, so golden lists document them in place.
func compileSchema(t *testing.T, d Dialect, fn func(*Schema)) []string {
	t.Helper()
	s := &Schema{}
	fn(s)
	if err := validateSchema("test", s); err != nil {
		t.Fatalf("declaration error: %v", err)
	}
	var out []string
	for _, op := range s.ops {
		stmts, err := d.compile(op)
		if err != nil {
			t.Fatalf("compile: %v", err)
		}
		for _, st := range stmts {
			if st.fn != nil {
				out = append(out, "-- "+describeStatement(st))
				continue
			}
			out = append(out, st.sql)
		}
	}
	return out
}

func assertSQL(t *testing.T, got []string, want []string) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("statement count = %d, want %d\ngot:\n%s", len(got), len(want), strings.Join(got, "\n---\n"))
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("statement %d:\n got: %s\nwant: %s", i+1, got[i], want[i])
		}
	}
}

// The showcase table exercises most column kinds, modifiers, conventional
// index names and the constrained foreign key in one declaration.
func showcase(s *Schema) {
	s.Create("users", func(t *Table) {
		t.ID()
		t.String("email").Unique()
		t.String("name", 100)
		t.Text("bio").Nullable()
		t.Boolean("active").Default(true)
		t.Decimal("balance", 10, 2).Default(0)
		t.Enum("role", "admin", "member").Default("member")
		t.JSON("settings").Nullable()
		t.ForeignID("team_id").Constrained().CascadeOnDelete()
		t.Timestamps()
		t.Index("name", "active")
	})
}

func TestPostgresCreateTable(t *testing.T) {
	got := compileSchema(t, Postgres, showcase)
	want := []string{
		`CREATE TABLE "users" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"email" VARCHAR(255) NOT NULL,
	"name" VARCHAR(100) NOT NULL,
	"bio" TEXT,
	"active" BOOLEAN NOT NULL DEFAULT TRUE,
	"balance" NUMERIC(10, 2) NOT NULL DEFAULT 0,
	"role" VARCHAR(255) NOT NULL DEFAULT 'member' CONSTRAINT "users_role_check" CHECK ("role" IN ('admin', 'member')),
	"settings" JSONB,
	"team_id" BIGINT NOT NULL,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	CONSTRAINT "users_team_id_foreign" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE
)`,
		`CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email")`,
		`CREATE INDEX "users_name_active_index" ON "users" ("name", "active")`,
	}
	assertSQL(t, got, want)
}

func TestMySQLCreateTable(t *testing.T) {
	got := compileSchema(t, MySQL, showcase)
	want := []string{
		"CREATE TABLE `users` (\n" +
			"\t`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,\n" +
			"\t`email` VARCHAR(255) NOT NULL,\n" +
			"\t`name` VARCHAR(100) NOT NULL,\n" +
			"\t`bio` LONGTEXT,\n" +
			"\t`active` TINYINT(1) NOT NULL DEFAULT TRUE,\n" +
			"\t`balance` DECIMAL(10, 2) NOT NULL DEFAULT 0,\n" +
			"\t`role` ENUM('admin', 'member') NOT NULL DEFAULT 'member',\n" +
			"\t`settings` JSON,\n" +
			"\t`team_id` BIGINT UNSIGNED NOT NULL,\n" +
			"\t`created_at` DATETIME(6),\n" +
			"\t`updated_at` DATETIME(6),\n" +
			"\tCONSTRAINT `users_team_id_foreign` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON DELETE CASCADE\n" +
			")",
		"CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`)",
		"CREATE INDEX `users_name_active_index` ON `users` (`name`, `active`)",
	}
	assertSQL(t, got, want)
}

func TestSQLiteCreateTable(t *testing.T) {
	got := compileSchema(t, SQLite, showcase)
	want := []string{
		`CREATE TABLE "users" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"email" VARCHAR(255) NOT NULL,
	"name" VARCHAR(100) NOT NULL,
	"bio" TEXT,
	"active" BOOLEAN NOT NULL DEFAULT TRUE,
	"balance" NUMERIC(10, 2) NOT NULL DEFAULT 0,
	"role" TEXT NOT NULL DEFAULT 'member' CONSTRAINT "users_role_check" CHECK ("role" IN ('admin', 'member')),
	"settings" TEXT,
	"team_id" INTEGER NOT NULL,
	"created_at" DATETIME,
	"updated_at" DATETIME,
	CONSTRAINT "users_team_id_foreign" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE
)`,
		`CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email")`,
		`CREATE INDEX "users_name_active_index" ON "users" ("name", "active")`,
	}
	assertSQL(t, got, want)
}

func TestPostgresAlterTable(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.Table("users", func(t *Table) {
			t.String("nickname", 50).Nullable().Comment("display name")
			t.RenameColumn("name", "full_name")
			t.DropColumn("bio")
			t.Index("nickname")
			t.DropUnique("email")
			t.Foreign("org_id").References("orgs").NullOnDelete()
			t.DropForeign("team_id")
		})
	})
	want := []string{
		`ALTER TABLE "users" ADD COLUMN "nickname" VARCHAR(50)`,
		`COMMENT ON COLUMN "users"."nickname" IS 'display name'`,
		`ALTER TABLE "users" RENAME COLUMN "name" TO "full_name"`,
		`ALTER TABLE "users" DROP COLUMN "bio"`,
		`CREATE INDEX "users_nickname_index" ON "users" ("nickname")`,
		`DROP INDEX "users_email_unique"`,
		`ALTER TABLE "users" ADD CONSTRAINT "users_org_id_foreign" FOREIGN KEY ("org_id") REFERENCES "orgs" ("id") ON DELETE SET NULL`,
		`ALTER TABLE "users" DROP CONSTRAINT "users_team_id_foreign"`,
	}
	assertSQL(t, got, want)
}

func TestMySQLAlterTable(t *testing.T) {
	got := compileSchema(t, MySQL, func(s *Schema) {
		s.Table("users", func(t *Table) {
			t.String("nickname", 50).Nullable().After("name")
			t.DropIndex("name", "active")
			t.DropForeign("team_id")
			t.DropPrimary()
		})
	})
	want := []string{
		"ALTER TABLE `users` ADD COLUMN `nickname` VARCHAR(50) AFTER `name`",
		"ALTER TABLE `users` DROP INDEX `users_name_active_index`",
		"ALTER TABLE `users` DROP FOREIGN KEY `users_team_id_foreign`",
		"ALTER TABLE `users` DROP PRIMARY KEY",
	}
	assertSQL(t, got, want)
}

func TestSQLiteRejectsConstraintAlterations(t *testing.T) {
	cases := map[string]func(*Table){
		"add foreign":  func(t *Table) { t.Foreign("org_id").References("orgs") },
		"drop foreign": func(t *Table) { t.DropForeign("team_id") },
		"add primary":  func(t *Table) { t.Primary("a", "b") },
		"drop primary": func(t *Table) { t.DropPrimary() },
	}
	for name, fn := range cases {
		t.Run(name, func(t *testing.T) {
			s := &Schema{}
			s.Table("users", fn)
			_, err := SQLite.compile(s.ops[0])
			if err == nil {
				t.Fatal("expected an explicit error, got none")
			}
			if !strings.Contains(err.Error(), "sqlite cannot") {
				t.Fatalf("error should explain the SQLite limitation, got: %v", err)
			}
		})
	}
}

func TestRenameAndDropCompile(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.Rename("old_users", "users")
		s.Drop("legacy")
		s.DropIfExists("maybe")
	})
	want := []string{
		`ALTER TABLE "old_users" RENAME TO "users"`,
		`DROP TABLE "legacy"`,
		`DROP TABLE IF EXISTS "maybe"`,
	}
	assertSQL(t, got, want)

	got = compileSchema(t, MySQL, func(s *Schema) { s.Rename("a", "b") })
	assertSQL(t, got, []string{"RENAME TABLE `a` TO `b`"})
}

func TestCompositePrimaryKeyAndRawColumn(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.Create("memberships", func(t *Table) {
			t.ForeignID("user_id").Constrained()
			t.ForeignID("team_id").Constrained()
			t.Column("location", "geography(point, 4326)").Nullable()
			t.Primary("user_id", "team_id")
		})
	})
	want := []string{
		`CREATE TABLE "memberships" (
	"user_id" BIGINT NOT NULL,
	"team_id" BIGINT NOT NULL,
	"location" geography(point, 4326),
	CONSTRAINT "memberships_pkey" PRIMARY KEY ("user_id", "team_id"),
	CONSTRAINT "memberships_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
	CONSTRAINT "memberships_team_id_foreign" FOREIGN KEY ("team_id") REFERENCES "teams" ("id")
)`,
	}
	assertSQL(t, got, want)
}

func TestDefaultRendering(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.Create("t", func(t *Table) {
			t.String("quoted").Default("it's")
			t.UUID("token").DefaultExpr("gen_random_uuid()")
			t.TimestampTz("seen_at").UseCurrent()
			t.Integer("nil_default").Nullable().Default(nil)
		})
	})
	want := []string{
		`CREATE TABLE "t" (
	"quoted" VARCHAR(255) NOT NULL DEFAULT 'it''s',
	"token" UUID NOT NULL DEFAULT (gen_random_uuid()),
	"seen_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"nil_default" INTEGER DEFAULT NULL
)`,
	}
	assertSQL(t, got, want)
}

func TestMySQLBackslashEscaping(t *testing.T) {
	got := compileSchema(t, MySQL, func(s *Schema) {
		s.Create("t", func(t *Table) {
			t.String("path").Default(`C:\logs`)
		})
	})
	want := []string{
		"CREATE TABLE `t` (\n\t`path` VARCHAR(255) NOT NULL DEFAULT 'C:\\\\logs'\n)",
	}
	assertSQL(t, got, want)

	// Postgres keeps backslashes verbatim (standard_conforming_strings).
	got = compileSchema(t, Postgres, func(s *Schema) {
		s.Create("t", func(t *Table) {
			t.String("path").Default(`C:\logs`)
		})
	})
	if !strings.Contains(got[0], `DEFAULT 'C:\logs'`) {
		t.Fatalf("postgres should not double backslashes, got: %s", got[0])
	}
}

func TestMySQLTimestampCurrentPrecision(t *testing.T) {
	got := compileSchema(t, MySQL, func(s *Schema) {
		s.Create("t", func(t *Table) {
			t.TimestampTz("created_at").UseCurrent().UseCurrentOnUpdate()
		})
	})
	want := []string{
		"CREATE TABLE `t` (\n\t`created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)\n)",
	}
	assertSQL(t, got, want)
}

func TestUnsupportedDefaultValueType(t *testing.T) {
	s := &Schema{}
	s.Create("t", func(t *Table) {
		t.String("bad").Default(struct{}{})
	})
	if _, err := Postgres.compile(s.ops[0]); err == nil || !strings.Contains(err.Error(), "DefaultExpr") {
		t.Fatalf("expected an error pointing to DefaultExpr, got: %v", err)
	}
}

func TestTableCommentAndRenameIndex(t *testing.T) {
	declare := func(s *Schema) {
		s.Create("events", func(t *Table) {
			t.ID()
			t.Comment("it's the event log")
		})
		s.Table("events", func(t *Table) {
			t.RenameIndex("events_at_index", "events_at_idx")
			t.Comment("updated")
		})
	}
	assertSQL(t, compileSchema(t, Postgres, declare), []string{
		`CREATE TABLE "events" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
)`,
		`COMMENT ON TABLE "events" IS 'it''s the event log'`,
		`ALTER INDEX "events_at_index" RENAME TO "events_at_idx"`,
		`COMMENT ON TABLE "events" IS 'updated'`,
	})
	assertSQL(t, compileSchema(t, MySQL, declare), []string{
		"CREATE TABLE `events` (\n\t`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY\n) COMMENT = 'it''s the event log'",
		"ALTER TABLE `events` RENAME INDEX `events_at_index` TO `events_at_idx`",
		"ALTER TABLE `events` COMMENT = 'updated'",
	})

	// SQLite ignores comments and refuses index renames explicitly.
	s := &Schema{}
	s.Create("events", func(t *Table) {
		t.ID()
		t.Comment("ignored")
	})
	stmts, err := SQLite.compile(s.ops[0])
	if err != nil || len(stmts) != 1 {
		t.Fatalf("sqlite create with comment = %v, %v", stmts, err)
	}
	s = &Schema{}
	s.Table("events", func(t *Table) { t.RenameIndex("a", "b") })
	if _, err := SQLite.compile(s.ops[0]); err == nil || !strings.Contains(err.Error(), "cannot rename index") {
		t.Fatalf("sqlite rename index should error clearly, got: %v", err)
	}

	// Renaming an index reverses to the opposite rename; changing a comment
	// in an alteration is irreversible.
	m := migrationOf(t, func(s *Schema) {
		s.Table("events", func(t *Table) { t.RenameIndex("a", "b") })
	})
	assertSQL(t, downSQL(t, Postgres, m), []string{`ALTER INDEX "b" RENAME TO "a"`})
	m = migrationOf(t, func(s *Schema) {
		s.Table("events", func(t *Table) { t.Comment("x") })
	})
	if _, err := m.downOps(); !errors.Is(err, ErrIrreversible) {
		t.Fatalf("comment change should be irreversible, got: %v", err)
	}
}

func TestAutoIncrementColumns(t *testing.T) {
	declare := func(s *Schema) {
		s.Create("counters", func(t *Table) {
			t.Integer("id").AutoIncrement()
			t.String("name")
		})
	}
	assertSQL(t, compileSchema(t, Postgres, declare), []string{
		`CREATE TABLE "counters" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" VARCHAR(255) NOT NULL
)`,
	})
	assertSQL(t, compileSchema(t, MySQL, declare), []string{
		"CREATE TABLE `counters` (\n\t`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,\n\t`name` VARCHAR(255) NOT NULL\n)",
	})
	assertSQL(t, compileSchema(t, SQLite, declare), []string{
		`CREATE TABLE "counters" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"name" VARCHAR(255) NOT NULL
)`,
	})

	// SmallInteger keeps its width on engines that distinguish it.
	small := compileSchema(t, Postgres, func(s *Schema) {
		s.Create("c", func(t *Table) { t.SmallInteger("id").AutoIncrement() })
	})
	if !strings.Contains(small[0], `"id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`) {
		t.Errorf("smallint identity, got: %s", small[0])
	}
}

func TestAutoIncrementDeclarationErrors(t *testing.T) {
	cases := map[string]func(*Schema){
		"non-integer": func(s *Schema) {
			s.Create("t", func(t *Table) { t.String("id").AutoIncrement() })
		},
		"with default": func(s *Schema) {
			s.Create("t", func(t *Table) { t.Integer("id").AutoIncrement().Default(7) })
		},
		"nullable": func(s *Schema) {
			s.Create("t", func(t *Table) { t.Integer("id").AutoIncrement().Nullable() })
		},
	}
	for name, up := range cases {
		t.Run(name, func(t *testing.T) {
			m := migrationOf(t, up)
			if _, err := m.upOps(); err == nil {
				t.Fatal("expected a declaration error, got none")
			}
		})
	}
}

func TestAutoIncrementConflicts(t *testing.T) {
	s := &Schema{}
	s.Create("t", func(t *Table) {
		t.ID()
		t.Integer("seq").AutoIncrement()
	})
	if _, err := Postgres.compile(s.ops[0]); err == nil || !strings.Contains(err.Error(), "more than one auto-incrementing") {
		t.Fatalf("two auto-increment columns should fail, got: %v", err)
	}

	s = &Schema{}
	s.Create("t", func(t *Table) {
		t.ID()
		t.String("code").Primary()
	})
	if _, err := Postgres.compile(s.ops[0]); err == nil || !strings.Contains(err.Error(), "combines an auto-incrementing primary key") {
		t.Fatalf("auto-increment plus another primary key should fail, got: %v", err)
	}

	s = &Schema{}
	s.Table("t", func(t *Table) { t.Integer("id").AutoIncrement() })
	if _, err := SQLite.compile(s.ops[0]); err == nil || !strings.Contains(err.Error(), "cannot add auto-increment") {
		t.Fatalf("sqlite adding an auto-increment column should fail clearly, got: %v", err)
	}
}

func TestIdentifierQuoting(t *testing.T) {
	if got := pgQ.ident(`we"ird`); got != `"we""ird"` {
		t.Errorf("postgres ident = %s", got)
	}
	if got := myQ.ident("we`ird"); got != "`we``ird`" {
		t.Errorf("mysql ident = %s", got)
	}
}

// Audit: SQLite ADD COLUMN restrictions that only bite on populated tables
// must fail at compile time.
func TestSQLiteAlterAddColumnGuards(t *testing.T) {
	cases := map[string]struct {
		declare func(*Table)
		want    string
	}{
		"stored generated": {
			func(t *Table) { t.String("summary").StoredAs("substr(body,1,100)") },
			"STORED generated column",
		},
		"use current": {
			func(t *Table) { t.TimestampTz("seen").Nullable().UseCurrent() },
			"non-constant default",
		},
		"default expr": {
			func(t *Table) { t.UUID("token").Nullable().DefaultExpr("hex(randomblob(16))") },
			"non-constant default",
		},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			s := &Schema{}
			s.Table("events", tc.declare)
			_, err := SQLite.compile(s.ops[0])
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("expected compile error mentioning %q, got: %v", tc.want, err)
			}
		})
	}
	// Virtual generated columns remain addable.
	s := &Schema{}
	s.Table("events", func(t *Table) {
		t.String("kind", 32).VirtualAs("json_extract(meta,'$.kind')").Nullable()
	})
	if _, err := SQLite.compile(s.ops[0]); err != nil {
		t.Fatalf("VIRTUAL generated columns are addable on SQLite: %v", err)
	}
}

// Audit: raw-typed auto-increment must be INTEGER on SQLite.
func TestSQLiteRawAutoIncrementRequiresInteger(t *testing.T) {
	s := &Schema{}
	s.Create("t", func(tb *Table) { tb.Column("id", "BIGINT").AutoIncrement() })
	if _, err := SQLite.compile(s.ops[0]); err == nil || !strings.Contains(err.Error(), "INTEGER") {
		t.Fatalf("BIGINT AUTOINCREMENT must fail at compile time, got: %v", err)
	}
	s = &Schema{}
	s.Create("t", func(tb *Table) { tb.Column("id", "integer").AutoIncrement() })
	if _, err := SQLite.compile(s.ops[0]); err != nil {
		t.Fatalf("a raw integer type (any case) is fine: %v", err)
	}
}
