package migrate

import (
	"strings"
	"testing"
)

func TestQualifiedTableNames(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.Create("analytics.events", func(t *Table) {
			t.ID()
			t.String("kind").Index()
			t.ForeignID("user_id").References("public.users").CascadeOnDelete()
			t.Enum("level", "info", "warn")
			t.Comment("event stream")
		})
		s.Table("analytics.events", func(t *Table) {
			t.DropIndex("kind")
			t.RenameColumn("kind", "category")
		})
		s.Rename("analytics.events", "analytics.event_log")
		s.DropIfExists("analytics.event_log")
	})
	want := []string{
		`CREATE TABLE "analytics"."events" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"kind" VARCHAR(255) NOT NULL,
	"user_id" BIGINT NOT NULL,
	"level" VARCHAR(255) NOT NULL CONSTRAINT "events_level_check" CHECK ("level" IN ('info', 'warn')),
	CONSTRAINT "events_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE CASCADE
)`,
		`CREATE INDEX "events_kind_index" ON "analytics"."events" ("kind")`,
		`COMMENT ON TABLE "analytics"."events" IS 'event stream'`,
		`DROP INDEX "analytics"."events_kind_index"`,
		`ALTER TABLE "analytics"."events" RENAME COLUMN "kind" TO "category"`,
		`ALTER TABLE "analytics"."events" RENAME TO "event_log"`,
		`DROP TABLE IF EXISTS "analytics"."event_log"`,
	}
	assertSQL(t, got, want)
}

func TestQualifiedRecreateStaysInSchema(t *testing.T) {
	got := compileSchema(t, SQLite, func(s *Schema) {
		s.Recreate("aux.items", func(t *Table) {
			t.ID()
			t.String("name").Unique()
		})
	})
	want := []string{
		`CREATE TABLE "aux"."items__migrate_new" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"name" VARCHAR(255) NOT NULL
)`,
		`INSERT INTO "aux"."items__migrate_new" ("id", "name") SELECT "id", "name" FROM "aux"."items"`,
		`-- capture the triggers of "aux"."items"`,
		`DROP TABLE "aux"."items"`,
		`ALTER TABLE "aux"."items__migrate_new" RENAME TO "items"`,
		// SQLite qualifies the index name, not the table.
		`CREATE UNIQUE INDEX "aux"."items_name_unique" ON "items" ("name")`,
		`-- recreate the captured triggers of "aux"."items"`,
	}
	assertSQL(t, got, want)
}

func TestQualifiedMySQLRename(t *testing.T) {
	got := compileSchema(t, MySQL, func(s *Schema) {
		s.Rename("warehouse.a", "warehouse.b")
	})
	assertSQL(t, got, []string{"RENAME TABLE `warehouse`.`a` TO `warehouse`.`b`"})
}

func TestQualifiedRecordsTable(t *testing.T) {
	f := newFakeDB()
	m := testMigrator(t, f, Postgres, twoTables(), WithTable("ops.schema_migrations"))
	if err := m.Up(t.Context()); err != nil {
		t.Fatalf("Up: %v", err)
	}
	if len(f.loggedContaining(`CREATE TABLE IF NOT EXISTS "ops"."schema_migrations"`)) != 1 {
		t.Errorf("records table should be schema-qualified, log:\n%s", strings.Join(f.logged(), "\n"))
	}
	if len(f.loggedContaining(`INSERT INTO "ops"."schema_migrations"`)) != 2 {
		t.Error("bookkeeping should target the qualified records table")
	}
}

// Audit M16: listTables sees only the current schema, so a records table
// qualified into another schema survived Fresh with every migration still
// recorded — the following Up then skipped everything and reported success
// over an empty database.
func TestFreshDropsQualifiedRecordsTable(t *testing.T) {
	f := newFakeDB()
	f.tables = []string{"users"}
	m := testMigrator(t, f, Postgres, twoTables(), WithTable("aux.schema_migrations"))
	if err := m.Fresh(t.Context()); err != nil {
		t.Fatalf("Fresh: %v", err)
	}
	if len(f.loggedContaining(`DROP TABLE IF EXISTS "aux"."schema_migrations"`)) != 1 {
		t.Errorf("the qualified records table must join the drop set, log:\n%s", strings.Join(f.logged(), "\n"))
	}
	if len(f.loggedContaining(`CREATE TABLE "users"`)) != 1 {
		t.Error("migrations should re-apply from scratch")
	}
}

// Audit: cross-schema renames silently stayed in the source schema on
// Postgres and SQLite while MySQL moved the table.
func TestCrossSchemaRenameRefused(t *testing.T) {
	s := &Schema{}
	s.Rename("public.orders", "archive.orders")
	if _, err := Postgres.compile(s.ops[0]); err == nil || !strings.Contains(err.Error(), "SET SCHEMA") {
		t.Fatalf("postgres must refuse cross-schema renames, got: %v", err)
	}
	if _, err := SQLite.compile(s.ops[0]); err == nil {
		t.Fatal("sqlite must refuse cross-schema rename")
	}
	if _, err := MySQL.compile(s.ops[0]); err != nil {
		t.Fatalf("mysql legitimately moves tables across databases: %v", err)
	}
	// Same-schema qualified renames keep working.
	s = &Schema{}
	s.Rename("analytics.a", "analytics.b")
	if _, err := Postgres.compile(s.ops[0]); err != nil {
		t.Fatalf("same-schema rename: %v", err)
	}
}

// Audit: RenameIndex ignored the table's schema on Postgres.
func TestRenameIndexQualified(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.Table("analytics.events", func(t *Table) {
			t.RenameIndex("events_kind_index", "events_category_index")
		})
	})
	assertSQL(t, got, []string{
		`ALTER INDEX "analytics"."events_kind_index" RENAME TO "events_category_index"`,
	})
}
