package migrate

import (
	"fmt"
	"strings"
)

// Table declares columns, indexes and foreign keys. Inside a Create call the
// declarations describe a new table; inside a Table call they describe changes
// to an existing one. Declaration methods never fail in place — mistakes are
// collected and reported together when the migration compiles, so the fluent
// style stays uncluttered.
type Table struct {
	table  string
	create *tableDef   // set inside Schema.Create
	alter  *alterTable // set inside Schema.Table
}

func (t *Table) errf(format string, a ...any) {
	err := fmt.Errorf(format, a...)
	if t.create != nil {
		t.create.errs = append(t.create.errs, err)
	} else {
		t.alter.errs = append(t.alter.errs, err)
	}
}

func (t *Table) addColumn(col *columnDef) *Column {
	if col.name == "" {
		t.errf("table %q declares a column with an empty name", t.table)
	}
	if t.create != nil {
		t.create.columns = append(t.create.columns, col)
	} else {
		t.alter.changes = append(t.alter.changes, &addColumn{col: col})
	}
	return &Column{def: col}
}

func (t *Table) addIndexDef(idx *indexDef) {
	if t.create != nil {
		t.create.indexes = append(t.create.indexes, idx)
	} else {
		t.alter.changes = append(t.alter.changes, &addIndex{idx: idx})
	}
}

func (t *Table) addForeignDef(fk *foreignDef) {
	if t.create != nil {
		t.create.fks = append(t.create.fks, fk)
	} else {
		t.alter.changes = append(t.alter.changes, &addForeign{fk: fk})
	}
}

func (t *Table) alterOnly(method string) bool {
	if t.alter == nil {
		t.errf("%s is only valid inside Schema.Table, not Schema.Create (table %q)", method, t.table)
		return false
	}
	return true
}

func optional[T any](v []T, def T) T {
	if len(v) > 0 {
		return v[0]
	}
	return def
}

// --- column declarations ---

// ID declares a 64-bit auto-incrementing primary key named "id" (or the given
// name) — shorthand for BigInteger(name).Unsigned().AutoIncrement(): BIGINT
// GENERATED BY DEFAULT AS IDENTITY on Postgres, BIGINT UNSIGNED
// AUTO_INCREMENT on MySQL, INTEGER AUTOINCREMENT on SQLite. For a different
// integer width, declare the column yourself:
//
//	t.Integer("id").AutoIncrement()
func (t *Table) ID(name ...string) *Column {
	return t.BigInteger(optional(name, "id")).Unsigned().AutoIncrement()
}

// String declares a VARCHAR column. The length defaults to 255.
func (t *Table) String(name string, length ...int) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindString, length: optional(length, 255)})
}

// Char declares a fixed-length CHAR column. The length defaults to 255.
func (t *Table) Char(name string, length ...int) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindChar, length: optional(length, 255)})
}

// Text declares an unbounded text column (TEXT, or LONGTEXT on MySQL where
// TEXT is capped at 64 KB).
func (t *Table) Text(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindText})
}

// TinyInteger declares an 8-bit integer (SMALLINT on Postgres, which has no
// 8-bit type).
func (t *Table) TinyInteger(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindTinyInt})
}

// SmallInteger declares a 16-bit integer.
func (t *Table) SmallInteger(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindSmallInt})
}

// Integer declares a 32-bit integer.
func (t *Table) Integer(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindInt})
}

// BigInteger declares a 64-bit integer.
func (t *Table) BigInteger(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindBigInt})
}

// Boolean declares a boolean column (TINYINT(1) on MySQL).
func (t *Table) Boolean(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindBool})
}

// Decimal declares an exact fixed-point column, e.g. Decimal("amount", 10, 2).
func (t *Table) Decimal(name string, precision, scale int) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindDecimal, precision: precision, scale: scale})
}

// Float declares a single-precision floating point column.
func (t *Table) Float(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindFloat})
}

// Double declares a double-precision floating point column.
func (t *Table) Double(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindDouble})
}

// Date declares a calendar date column.
func (t *Table) Date(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindDate})
}

// Time declares a time-of-day column.
func (t *Table) Time(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindTime})
}

// DateTime declares a wall-clock timestamp without time zone: TIMESTAMP on
// Postgres, DATETIME(6) on MySQL.
func (t *Table) DateTime(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindDateTime})
}

// Timestamp is an alias for DateTime, for schemas that prefer the name.
func (t *Table) Timestamp(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindTimestamp})
}

// TimestampTz declares a point-in-time column: TIMESTAMPTZ on Postgres (the
// recommended default for recording instants), DATETIME(6) on MySQL, which
// has no time-zone-aware type.
func (t *Table) TimestampTz(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindTimestampTz})
}

// JSON declares a JSON document column, mapped to each dialect's preferred
// binary representation: JSONB on Postgres, JSON on MySQL, TEXT on SQLite.
// For Postgres's plain json type, use Column(name, "json").
func (t *Table) JSON(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindJSON})
}

// UUID declares a UUID column (native on Postgres, CHAR(36) elsewhere).
func (t *Table) UUID(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindUUID})
}

// Binary declares a binary blob column.
func (t *Table) Binary(name string) *Column {
	return t.addColumn(&columnDef{name: name, kind: kindBinary})
}

// Enum declares a column restricted to the given values: a native ENUM on
// MySQL, VARCHAR plus a named CHECK constraint elsewhere.
func (t *Table) Enum(name string, values ...string) *Column {
	if len(values) == 0 {
		t.errf("enum column %q of table %q declares no values", name, t.table)
	}
	return t.addColumn(&columnDef{name: name, kind: kindEnum, enumVals: values})
}

// Column declares a column with a dialect type written verbatim, for types
// the portable set does not cover, e.g. Column("location", "geography(point)").
func (t *Table) Column(name, sqlType string) *Column {
	if sqlType == "" {
		t.errf("column %q of table %q declares an empty type", name, t.table)
	}
	return t.addColumn(&columnDef{name: name, kind: kindRaw, rawType: sqlType})
}

// --- convenience declarations ---

// Timestamps declares nullable created_at and updated_at TimestampTz columns.
func (t *Table) Timestamps() {
	t.TimestampTz("created_at").Nullable()
	t.TimestampTz("updated_at").Nullable()
}

// SoftDeletes declares a nullable deleted_at TimestampTz column (or the given
// name) for soft-deletion schemes.
func (t *Table) SoftDeletes(name ...string) *Column {
	return t.TimestampTz(optional(name, "deleted_at")).Nullable()
}

// ForeignID declares a column typed to match ID primary keys, ready to be
// constrained to its parent table:
//
//	t.ForeignID("user_id").Constrained()                      // references users.id
//	t.ForeignID("author_id").References("users")               // explicit table
//	t.ForeignID("user_id").Constrained().CascadeOnDelete()
func (t *Table) ForeignID(name string) *ForeignColumn {
	col := &columnDef{name: name, kind: kindBigInt, unsigned: true}
	c := t.addColumn(col)
	return &ForeignColumn{Column: c, table: t}
}

// --- indexes and keys ---

// Index declares an index over the given columns, named
// {table}_{columns}_index unless renamed with Name.
func (t *Table) Index(columns ...string) *Index {
	idx := &indexDef{columns: columns}
	if len(columns) == 0 {
		t.errf("index on table %q declares no columns", t.table)
	}
	t.addIndexDef(idx)
	return &Index{def: idx}
}

// Unique declares a unique index over the given columns, named
// {table}_{columns}_unique unless renamed with Name.
func (t *Table) Unique(columns ...string) *Index {
	idx := &indexDef{columns: columns, unique: true}
	if len(columns) == 0 {
		t.errf("unique index on table %q declares no columns", t.table)
	}
	t.addIndexDef(idx)
	return &Index{def: idx}
}

// Primary declares a composite primary key. For the common single
// auto-incrementing key, use ID instead.
func (t *Table) Primary(columns ...string) {
	if len(columns) == 0 {
		t.errf("primary key on table %q declares no columns", t.table)
		return
	}
	if t.create != nil {
		t.create.primary = columns
	} else {
		t.alter.changes = append(t.alter.changes, &addPrimary{columns: columns})
	}
}

// Check declares a named CHECK constraint over an expression written
// verbatim:
//
//	t.Check("orders_price_positive", "price > 0")
//
// The name is required — anonymous constraints cannot be dropped or reasoned
// about later. Inside Schema.Table, SQLite cannot add constraints; use
// Schema.Recreate there.
func (t *Table) Check(name, expr string) {
	if name == "" || expr == "" {
		t.errf("check constraint on table %q needs both a name and an expression", t.table)
		return
	}
	chk := &checkDef{name: name, expr: expr}
	if t.create != nil {
		t.create.checks = append(t.create.checks, chk)
	} else {
		t.alter.changes = append(t.alter.changes, &addCheck{chk: chk})
	}
}

// Foreign declares a foreign key on existing columns:
//
//	t.Foreign("user_id").References("users")        // references users.id
//	t.Foreign("a", "b").References("parents", "a", "b")
//
// For declaring the column and its key together, prefer ForeignID.
func (t *Table) Foreign(columns ...string) *ForeignKey {
	fk := &foreignDef{columns: columns}
	if len(columns) == 0 {
		t.errf("foreign key on table %q declares no columns", t.table)
	}
	t.addForeignDef(fk)
	return &ForeignKey{def: fk, table: t}
}

// Comment attaches a comment to the table itself (Postgres and MySQL; SQLite
// has no table comments and ignores it). Inside Schema.Table, changing a
// comment discards the previous one and is therefore irreversible.
func (t *Table) Comment(comment string) {
	if t.create != nil {
		t.create.comment = comment
		return
	}
	t.alter.changes = append(t.alter.changes, &setTableComment{comment: comment})
}

// --- alterations (Schema.Table only) ---

// RenameIndex renames an index. It reverses to the opposite rename. SQLite
// cannot rename indexes; dropping and re-declaring is the portable route.
func (t *Table) RenameIndex(from, to string) {
	if t.alterOnly("RenameIndex") {
		t.alter.changes = append(t.alter.changes, &renameIndex{from: from, to: to})
	}
}

// RenameColumn renames a column. It reverses to the opposite rename.
func (t *Table) RenameColumn(from, to string) {
	if t.alterOnly("RenameColumn") {
		t.alter.changes = append(t.alter.changes, &renameColumn{from: from, to: to})
	}
}

// DropColumn removes the given columns. Dropping is irreversible: rolling
// back requires an explicit down migration declared with WithDown.
//
// SQLite refuses to drop columns that are indexed or referenced by other
// schema objects; such changes need a manual table rebuild.
func (t *Table) DropColumn(names ...string) {
	if !t.alterOnly("DropColumn") {
		return
	}
	for _, name := range names {
		t.alter.changes = append(t.alter.changes, &dropColumn{name: name})
	}
}

// DropIndex removes the index that Index would have created on the given
// columns, using the conventional {table}_{columns}_index name. For an index
// with a custom name, use DropIndexByName.
func (t *Table) DropIndex(columns ...string) {
	if t.alterOnly("DropIndex") {
		t.alter.changes = append(t.alter.changes, &dropIndex{name: indexName(t.table, columns, false)})
	}
}

// DropUnique removes the unique index that Unique would have created on the
// given columns, using the conventional {table}_{columns}_unique name.
func (t *Table) DropUnique(columns ...string) {
	if t.alterOnly("DropUnique") {
		t.alter.changes = append(t.alter.changes, &dropIndex{name: indexName(t.table, columns, true)})
	}
}

// DropIndexByName removes an index by its exact name.
func (t *Table) DropIndexByName(name string) {
	if t.alterOnly("DropIndexByName") {
		t.alter.changes = append(t.alter.changes, &dropIndex{name: name})
	}
}

// DropForeign removes the foreign key that Foreign or Constrained would have
// created on the given columns, using the conventional
// {table}_{columns}_foreign name. For a key with a custom name, use
// DropForeignByName.
func (t *Table) DropForeign(columns ...string) {
	if t.alterOnly("DropForeign") {
		t.alter.changes = append(t.alter.changes, &dropForeign{name: foreignName(t.table, columns)})
	}
}

// DropForeignByName removes a foreign key by its exact name.
func (t *Table) DropForeignByName(name string) {
	if t.alterOnly("DropForeignByName") {
		t.alter.changes = append(t.alter.changes, &dropForeign{name: name})
	}
}

// DropCheck removes a CHECK constraint by name. Dropping discards the
// expression and is irreversible.
func (t *Table) DropCheck(name string) {
	if t.alterOnly("DropCheck") {
		t.alter.changes = append(t.alter.changes, &dropCheck{name: name})
	}
}

// DropPrimary removes the table's primary key.
func (t *Table) DropPrimary() {
	if t.alterOnly("DropPrimary") {
		t.alter.changes = append(t.alter.changes, &dropPrimary{})
	}
}

// guessParentTable derives the referenced table from a foreign key column
// name: user_id → users, category_id → categories. The heuristic covers
// regular English plurals; for anything else pass the table explicitly.
func guessParentTable(column string) string {
	base := strings.TrimSuffix(column, "_id")
	if base == column || base == "" {
		return ""
	}
	switch {
	case len(base) >= 2 && strings.HasSuffix(base, "y") && !strings.ContainsRune("aeiou", rune(base[len(base)-2])):
		return base[:len(base)-1] + "ies"
	case strings.HasSuffix(base, "s") || strings.HasSuffix(base, "x") || strings.HasSuffix(base, "z") ||
		strings.HasSuffix(base, "ch") || strings.HasSuffix(base, "sh"):
		return base + "es"
	default:
		return base + "s"
	}
}
