package migrate

import (
	"errors"
	"strings"
	"testing"
)

func TestGeneratedColumns(t *testing.T) {
	declare := func(s *Schema) {
		s.Create("people", func(t *Table) {
			t.ID()
			t.String("first")
			t.String("last")
			t.String("full").StoredAs("first || ' ' || last")
			t.JSON("meta").Nullable()
			t.String("kind", 32).VirtualAs("json_extract(meta, '$.kind')").Nullable()
		})
	}
	pg := compileSchema(t, Postgres, declare)[0]
	for _, frag := range []string{
		`"full" VARCHAR(255) GENERATED ALWAYS AS (first || ' ' || last) STORED NOT NULL`,
		`"kind" VARCHAR(32) GENERATED ALWAYS AS (json_extract(meta, '$.kind')) VIRTUAL`,
	} {
		if !strings.Contains(pg, frag) {
			t.Errorf("postgres missing %q in:\n%s", frag, pg)
		}
	}
	my := compileSchema(t, MySQL, declare)[0]
	if !strings.Contains(my, "`full` VARCHAR(255) GENERATED ALWAYS AS (first || ' ' || last) STORED NOT NULL") {
		t.Errorf("mysql stored generated column, got:\n%s", my)
	}
	lite := compileSchema(t, SQLite, declare)[0]
	if !strings.Contains(lite, `"full" VARCHAR(255) NOT NULL GENERATED ALWAYS AS (first || ' ' || last) STORED`) {
		t.Errorf("sqlite stored generated column, got:\n%s", lite)
	}
}

func TestGeneratedColumnValidation(t *testing.T) {
	cases := map[string]func(*Table){
		"with default":        func(t *Table) { t.String("x").StoredAs("a").Default("y") },
		"with use current":    func(t *Table) { t.Timestamp("x").StoredAs("a").UseCurrent() },
		"with auto increment": func(t *Table) { t.Integer("x").AutoIncrement().StoredAs("a") },
	}
	for name, decl := range cases {
		t.Run(name, func(t *testing.T) {
			m := migrationOf(t, func(s *Schema) { s.Create("t", func(tb *Table) { decl(tb) }) })
			if _, err := m.upOps(); err == nil {
				t.Fatal("expected a declaration error")
			}
		})
	}
}

func TestCheckConstraints(t *testing.T) {
	got := compileSchema(t, Postgres, func(s *Schema) {
		s.Create("orders", func(t *Table) {
			t.ID()
			t.Decimal("price", 10, 2)
			t.Check("orders_price_positive", "price > 0")
		})
		s.Table("orders", func(t *Table) {
			t.Check("orders_price_sane", "price < 1000000")
			t.DropCheck("orders_price_positive")
		})
	})
	want := []string{
		`CREATE TABLE "orders" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"price" NUMERIC(10, 2) NOT NULL,
	CONSTRAINT "orders_price_positive" CHECK (price > 0)
)`,
		`ALTER TABLE "orders" ADD CONSTRAINT "orders_price_sane" CHECK (price < 1000000)`,
		`ALTER TABLE "orders" DROP CONSTRAINT "orders_price_positive"`,
	}
	assertSQL(t, got, want)

	my := compileSchema(t, MySQL, func(s *Schema) {
		s.Table("orders", func(t *Table) {
			t.Check("c1", "price > 0")
			t.DropCheck("c1")
		})
	})
	assertSQL(t, my, []string{
		"ALTER TABLE `orders` ADD CONSTRAINT `c1` CHECK (price > 0)",
		"ALTER TABLE `orders` DROP CHECK `c1`",
	})
}

func TestCheckReversesAndSQLiteRefusesAlter(t *testing.T) {
	m := migrationOf(t, func(s *Schema) {
		s.Table("orders", func(t *Table) { t.Check("c1", "price > 0") })
	})
	assertSQL(t, downSQL(t, Postgres, m), []string{`ALTER TABLE "orders" DROP CONSTRAINT "c1"`})

	m = migrationOf(t, func(s *Schema) {
		s.Table("orders", func(t *Table) { t.DropCheck("c1") })
	})
	if _, err := m.downOps(); !errors.Is(err, ErrIrreversible) {
		t.Fatalf("dropping a check should be irreversible, got %v", err)
	}

	s := &Schema{}
	s.Table("orders", func(t *Table) { t.Check("c1", "price > 0") })
	if _, err := SQLite.compile(s.ops[0]); err == nil || !strings.Contains(err.Error(), "Schema.Recreate") {
		t.Fatalf("sqlite should refuse and point at Recreate, got: %v", err)
	}

	// Anonymous checks are a declaration error (the Alembic lesson: unnamed
	// constraints cannot be addressed later).
	bad := migrationOf(t, func(s *Schema) {
		s.Create("t", func(tb *Table) {
			tb.ID()
			tb.Check("", "price > 0")
		})
	})
	if _, err := bad.upOps(); err == nil {
		t.Fatal("anonymous checks must be rejected")
	}
}

func TestRecreateCopyFromAndGenerated(t *testing.T) {
	got := compileSchema(t, SQLite, func(s *Schema) {
		s.Recreate("events", func(t *Table) {
			t.ID()
			t.Integer("age_years").CopyFrom("CAST(age AS INTEGER)")
			t.String("label").StoredAs("'ev-' || id")
			t.Check("events_age_positive", "age_years >= 0")
		})
	})
	want := []string{
		`CREATE TABLE "events__migrate_new" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"age_years" INTEGER NOT NULL,
	"label" VARCHAR(255) NOT NULL GENERATED ALWAYS AS ('ev-' || id) STORED,
	CONSTRAINT "events_age_positive" CHECK (age_years >= 0)
)`,
		// The generated column fills itself; age_years copies via the cast.
		`INSERT INTO "events__migrate_new" ("id", "age_years") SELECT "id", CAST(age AS INTEGER) FROM "events"`,
		`DROP TABLE "events"`,
		`ALTER TABLE "events__migrate_new" RENAME TO "events"`,
	}
	assertSQL(t, got, want)
}

func TestCopyFromSkipCopyConflict(t *testing.T) {
	m := migrationOf(t, func(s *Schema) {
		s.Recreate("t", func(tb *Table) {
			tb.ID()
			tb.String("x").CopyFrom("y").SkipCopy()
		})
	})
	if _, err := m.upOps(); err == nil {
		t.Fatal("CopyFrom plus SkipCopy must be a declaration error")
	}
}
